Update repo URL on DiskOS loading screen
LIKO-12/LIKO-12 pull request #204
Opened 2018-09-05 04:05 UTC by leereilly

**Type:**
`Typo fix`

**Description:**

Updates the GitHub URL on the loading screen from:

`http://github.com/ramilego4game/liko12`

to:

`https://github.com/LIKO-12/LIKO-12`

**Screenshots:**

<img width="576" alt="screen_shot_2018-09-04_at_8_59_16_pm" src="https://user-images.githubusercontent.com/121322/45070408-f4dc0900-b085-11e8-8ce9-e9a6307365cc.png">

**Modified Section:**
`DiskOS`

2018-09-05 04:59 UTC, Positive07 commented
Thanks for rising this issue, moving to an organization means changing a lot of links, and as you may noticed some passed below Rami's radar in the short time he had to work on it.

I searched through the repo and found a bunch of other similar problems:
[DiskOS/System/faketerminal.lua:17](https://github.com/LIKO-12/LIKO-12/blob/master/OS/DiskOS/System/faketerminal.lua#L17)
[GameDiskOS/System/faketerminal.lua:17](https://github.com/LIKO-12/LIKO-12/blob/master/OS/GameDiskOS/System/faketerminal.lua#L17)
[DiskOS/Programs/Disks/build.lua:31](https://github.com/LIKO-12/LIKO-12/blob/master/OS/DiskOS/Programs/Disks/build.lua#L31)
[DiskOS/Programs/Disks/build.lua:41](https://github.com/LIKO-12/LIKO-12/blob/master/OS/DiskOS/Programs/Disks/build.lua#L41)

We can either fix them all in this PR or just merge and then fix them later... I may do it tonight

2018-09-05 19:38 UTC, RamiLego4Game commented
Thanks for noticing this @leereilly, and Thanks @Positive07 for searching about other broken links !
Please change the one in the terminal to https://liko-12.github.io/ not https://github.com/LIKO-12/LIKO-12

2018-09-05 19:40 UTC, Rami-Sabbagh requested changes
Please change it to https://LIKO-12.github.io/ instead.

2018-09-05 19:56 UTC, leereilly commented
You're most welcome! Sounds good; I'll take another pass tonight 👍

2018-09-29 20:05 UTC, closed without merging

2018-09-29 20:06 UTC, Positive07 commented
I rebased and squashed this and merged it into master. Thanks a lot @leereilly